openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/recipes:
    get:
      tags:
      - recipify-controller
      operationId: recipes
      parameters:
      - name: page
        in: query
        description: Zero-based page index (0..N)
        schema:
          type: integer
          default: 0
      - name: size
        in: query
        description: The size of the page to be returned
        schema:
          type: integer
          default: 20
      - name: sort
        in: query
        description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponseRecipeDto'
components:
  schemas:
    CategoryDto:
      required:
      - description
      - title
      - type
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        description:
          type: string
    DifficultyLevel:
      type: object
    PageResponseRecipeDto:
      required:
      - content
      - hasNext
      - hasPrevious
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/RecipeDto'
        hasNext:
          type: boolean
        hasPrevious:
          type: boolean
    RecipeDto:
      required:
      - categories
      - cookTime
      - difficulty
      - headline
      - id
      - preparationTime
      - title
      - userFullname
      type: object
      properties:
        id:
          type: integer
          format: int64
        userFullname:
          type: string
        title:
          type: string
        headline:
          type: string
        preparationTime:
          type: integer
          format: int32
        cookTime:
          type: integer
          format: int32
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategoryDto'
        difficulty:
          $ref: '#/components/schemas/DifficultyLevel'
